export const ENVIRONMENT_VARIABLE_NAMES = {
    FORESIGHT_CLI_RUN_ID: 'FORESIGHT_CLI_RUN_ID',

    /** Github */
    GITHUB_REPOSITORY_ENV_VAR_NAME: 'GITHUB_REPOSITORY',
    GITHUB_HEAD_REF_ENV_VAR_NAME: 'GITHUB_HEAD_REF',
    GITHUB_WORKFLOW_REF_ENV_VAR_NAME: 'GITHUB_WORKFLOW_REF',
    GITHUB_REF_ENV_VAR_NAME: 'GITHUB_REF',
    GITHUB_EVENT_PATH_ENV_VAR_NAME: 'GITHUB_EVENT_PATH',
    GITHUB_SHA_ENV_VAR_NAME: 'GITHUB_SHA',
    GITHUB_RUN_ID_ENV_VAR_NAME: 'GITHUB_RUN_ID',
    GITHUB_RUN_ATTEMPT_ENV_VAR_NAME: 'GITHUB_RUN_ATTEMPT',
    GITHUB_WORKFLOW_NAME_ENV_VAR_NAME: 'GITHUB_WORKFLOW',
    GITHUB_RUNNER_NAME_ENV_VAR_NAME: 'RUNNER_NAME',
    INVOCATION_ID_ENV_VAR_NAME: 'INVOCATION_ID',

    /** Github Foresight Action */
    FORESIGHT_WORKFLOW_JOB_ID: 'FORESIGHT_WORKFLOW_JOB_ID',
    FORESIGHT_WORKFLOW_JOB_NAME: 'FORESIGHT_WORKFLOW_JOB_NAME',

    /** TravisCI */
    TRAVIS_ENV_VAR_NAME: 'TRAVIS',
    TRAVIS_REPO_SLUG_VAR_NAME: 'TRAVIS_REPO_SLUG',
    TRAVIS_PULL_REQUEST_BRANCH_ENV_VAR_NAME: 'TRAVIS_PULL_REQUEST_BRANCH',
    TRAVIS_BRANCH_ENV_VAR_NAME: 'TRAVIS_BRANCH',
    TRAVIS_COMMIT_ENV_VAR_NAME: 'TRAVIS_COMMIT',
    TRAVIS_COMMIT_MESSAGE_ENV_VAR_NAME: 'TRAVIS_COMMIT_MESSAGE',
    TRAVIS_BUILD_WEB_URL_ENV_VAR_NAME: 'TRAVIS_BUILD_WEB_URL',
    TRAVIS_BUILD_ID_ENV_VAR_NAME: 'TRAVIS_BUILD_ID',

    /** Jenkins */
    JENKINS_HOME_ENV_VAR_NAME: 'JENKINS_HOME',
    JENKINS_URL_ENV_VAR_NAME: 'JENKINS_URL',
    GIT_URL_ENV_VAR_NAME: 'GIT_URL',
    GIT_URL_1_ENV_VAR_NAME: 'GIT_URL_1',
    GIT_BRANCH_ENV_VAR_NAME: 'GIT_BRANCH',
    GIT_COMMIT_ENV_VAR_NAME: 'GIT_COMMIT',
    JOB_NAME_ENV_VAR_NAME: 'JOB_NAME',
    BUILD_ID_ENV_VAR_NAME: 'BUILD_ID',

    /** Gitlab */
    GITLAB_CI_ENV_VAR_NAME: 'GITLAB_CI',
    CI_REPOSITORY_URL_ENV_VAR_NAME: 'CI_REPOSITORY_URL',
    CI_COMMIT_BRANCH_ENV_VAR_NAME: 'CI_COMMIT_BRANCH',
    CI_COMMIT_REF_NAME_ENV_VAR_NAME: 'CI_COMMIT_REF_NAME',
    CI_COMMIT_SHA_ENV_VAR_NAME: 'CI_COMMIT_SHA',
    CI_COMMIT_MESSAGE_ENV_VAR_NAME: 'CI_COMMIT_MESSAGE',
    CI_JOB_ID_ENV_VAR_NAME: 'CI_JOB_ID',
    CI_JOB_URL_ENV_VAR_NAME: 'CI_JOB_URL',

    /** CircleCI */
    CIRCLECI_ENV_VAR_NAME: 'CIRCLECI',
    CIRCLE_REPOSITORY_URL_ENV_VAR_NAME: 'CIRCLE_REPOSITORY_URL',
    CIRCLE_BRANCH_ENV_VAR_NAME:  'CIRCLE_BRANCH',
    CIRCLE_SHA1_ENV_VAR_NAME: 'CIRCLE_SHA1',
    CIRCLE_BUILD_URL_ENV_VAR_NAME: 'CIRCLE_BUILD_URL',
    CIRCLE_BUILD_NUM_ENV_VAR_NAME: 'CIRCLE_BUILD_NUM',

    /** Bitbucket */
    BITBUCKET_GIT_HTTP_ORIGIN_ENV_VAR_NAME: 'BITBUCKET_GIT_HTTP_ORIGIN',
    BITBUCKET_GIT_SSH_ORIGIN_ENV_VAR_NAME: 'BITBUCKET_GIT_SSH_ORIGIN',
    BITBUCKET_BRANCH_ENV_VAR_NAME: 'BITBUCKET_BRANCH',
    BITBUCKET_COMMIT_ENV_VAR_NAME: 'BITBUCKET_COMMIT',
    BITBUCKET_BUILD_NUMBER_ENV_VAR_NAME: 'BITBUCKET_BUILD_NUMBER',
}