export default {
    THUNDRA_APIKEY: 'THUNDRA_APIKEY',
    THUNDRA_UPLOADER_LOG_LEVEL: 'THUNDRA_UPLOADER_LOG_LEVEL',
    THUNDRA_AGENT_TEST_PROJECT_ID: 'THUNDRA_AGENT_TEST_PROJECT_ID',
    THUNDRA_UPLOADER_REPORT_DIR: 'THUNDRA_UPLOADER_REPORT_DIR',
    THUNDRA_ARTIFACT_UPLOADER_URL: 'THUNDRA_ARTIFACT_UPLOADER_URL',
    THUNDRA_UPLOADER_SIZE_MAX: 'THUNDRA_UPLOADER_SIZE_MAX',
    THUNDRA_TMP: 'THUNDRA_TMP',
};