export default {
    THUNDRA_APIKEY: 'THUNDRA_APIKEY',
    THUNDRA_AGENT_TEST_PROJECT_ID: 'THUNDRA_AGENT_TEST_PROJECT_ID',
    THUNDRA_AGENT_TEST_RUN_ID: 'THUNDRA_AGENT_TEST_RUN_ID',
    THUNDRA_UPLOADER_TYPE: 'THUNDRA_UPLOADER_TYPE',
    THUNDRA_UPLOADER_FRAMEWORK: 'THUNDRA_UPLOADER_FRAMEWORK', 
    THUNDRA_UPLOADER_REPORT_DIR: 'THUNDRA_UPLOADER_REPORT_DIR',
    THUNDRA_UPLOADER_SIGNER_URL: 'THUNDRA_UPLOADER_SIGNER_URL',
    THUNDRA_UPLOADER_SIZE_MAX: 'THUNDRA_UPLOADER_SIZE_MAX',
    THUNDRA_UPLOADER_LOG_LEVEL: 'THUNDRA_UPLOADER_LOG_LEVEL',
};